#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [[ "${1:-}" == "--no-fix" ]]; then
  ruff format . --check
  ruff check .
else
  ruff format .
  ruff check . --fix
fi
mypy --strict custom_components/retry
