#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --upgrade pip --root-user-action ignore
python3 -m pip install uv --root-user-action ignore
uv pip install --system --prerelease allow pytest-homeassistant-custom-component
uv pip install --system --upgrade -r requirements.txt

prek install
