#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --upgrade pip --root-user-action ignore
python3 -m pip install uv --root-user-action ignore
uv pip install --system -r requirements.txt
